import "./globals.css";
import Navbar from "./components/Navbar";
import { Providers } from "./providers";
import UserDetails from "./components/UserDetails";
import { ThemeProvider } from "@/components/ThemeProvider";
import ToggleMode from "./components/ToggleMode";
import ApprovedContextProvider from "./context/ApprovedContext";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Providers>
						<ApprovedContextProvider>
							<Navbar />
							<UserDetails />
							{children}
							<ToggleMode />
						</ApprovedContextProvider>
					</Providers>
				</ThemeProvider>
			</body>
		</html>
	);
}
