import "./globals.css";
import Navbar from "./components/Navbar";
import { Providers } from "./providers";
import UserDetails from "./components/UserDetails";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<Navbar />
					<UserDetails />
					{children}
				</Providers>
			</body>
		</html>
	);
}
